advanced:

  - name: backbone_layers
    settings:
      activation_checkpoint_layers:
        - ForteBackboneLayer
      optimization_barrier_layers:
        - ForteBackboneLayer
      scan_layers: layers
      is_layer_pure: true
      offload_tensors: 
        - backbone_decoder_input

  - name: output_layers
    settings:
      activation_checkpoint_layers:
        - ForteOutputLayer
      optimization_barrier_layers:
        - ForteOutputLayer
      scan_layers: layers
      is_layer_pure: true
      offload_tensors: 
        - output_decoder_input

  - name: bidirectional_head
    settings:
      activation_checkpoint_layers:
        - BidirectionalDecoderLayer
      optimization_barrier_layers:
        - BidirectionalDecoderLayer
      scan_layers: layers.layers
      is_layer_pure: true
      offload_tensors: 
        - bidirectional_head_input
