advanced:

  - name: model.layers
    settings:
      activation_checkpoint_layers:
        - LlamaDecoderLayer
      optimization_barrier_layers:
        - LlamaDecoderLayer
      scan_layers: layers
      is_layer_pure: true
      # offload_tensors: 
      #   - decoder_input