advanced:

  - name: self
    settings:
      activation_checkpoint_layers:
        - LlamaDecoderLayer
      optimization_barrier_layers:
        - LlamaDecoderLayer
      scan_layers: model.layers
      is_layer_pure: true
      offload_tensors:
        - decoder_input

  - name: bidirectional_head
    settings:
      activation_checkpoint_layers:
        - BidirectionalDecoderLayer
      optimization_barrier_layers:
        - BidirectionalDecoderLayer
      scan_layers: layers
      is_layer_pure: true
      offload_tensors:
        - bidirectional_head_input
