advanced:

  - name: backbone_layers
    settings:
      activation_checkpoint_layers:
        - SlitherBackboneLayer
      optimization_barrier_layers:
        - SlitherBackboneLayer
      scan_layers: layers
      is_layer_pure: true
      # offload_tensors:
      #   - slither_backbone_layer_input

  - name: output_layers
    settings:
      activation_checkpoint_layers:
        - SlitherOutputLayer
      optimization_barrier_layers:
        - SlitherOutputLayer
      scan_layers: layers
      is_layer_pure: true
      # offload_tensors:
      #   - slither_output_layer_input

  - name: memory_layers
    settings:
      activation_checkpoint_layers:
        - SlitherMemoryLayer
      optimization_barrier_layers:
        - SlitherMemoryLayer
      scan_layers: layers
      is_layer_pure: true
      # offload_tensors:
      #   - slither_memory_layer_input
