defaults:
  - llama3p2-1b
  - override sharding: fo-ittt-fsdp
  - override remat: fo-ittt
  - _self_


type: fo_ittt.FoItttModel


fast_weight_size: 1536
base_lr: 3.0e-4
grad_rms_eps: 1.0e-12
state_dtype: float32

disable_fast_weights: false

num_bidirectional_layers: 4
pad_attention_bias_value: -1000.0
