defaults:
  - llama3p2-1b
  - override sharding: forte-fsdp
  - override remat: forte
  - _self_


type: forte.ForteModel


fast_weight_size: 1536

base_lr: 1e-3

grad_rms_eps: 1.0e-12

num_output_layers: 4
num_bidirectional_layers: 6

pad_attention_bias_value: -1000.0
