defaults:
  - llama3p2-1b
  - override sharding: forte-fsdp
  - override remat: forte
  - _self_


type: forte.ForteModel


fast_weight_size: 1024

base_lr: 0.010
lr_init_std: 0.5

grad_rms_eps: 1.0e-12

num_output_layers: 4
num_bidirectional_layers: 4

pad_attention_bias_value: -1000.0
