defaults:
  - llama3p2-1b
  - override sharding: oloop-fsdp
  - override remat: llama-scan
  - _self_


type: oloop_lora.OLoopLoRAModel


fast_weight_rank: 24

base_lr: 3.0e-4
momentum_beta: 0.95

grad_rms_eps: 1.0e-12

momentum_dtype: float32
state_dtype: float32
