defaults:
  - llama3p2-1b
  - override sharding: oloop-fsdp
  - override remat: llama-scan
  - _self_


type: oloop.OLoopModel


fast_weight_size: 1024

base_lr: 1.0e-4
momentum_beta: 0.9

grad_rms_eps: 1e-12

momentum_dtype: bfloat16
state_dtype: float32
