defaults:
  - llama3p2-1b
  - override sharding: piano-fsdp
  - override remat: llama-scan
  - _self_


type: piano.PianoModel


fast_weight_size: 1024
base_lr: 1e-3

pool_size: 1024
mixer_size: 5

grad_rms_eps: 1.0e-12
