defaults:
  - llama3p2-test
  - override sharding: recurrent-fsdp
  - override remat: recurrent
  - _self_


type: recurrent.RecurrentModel


fast_weight_size: 64

base_lr: 0.015
lr_init_std: 0.5

grad_rms_eps: 1.0e-12

num_output_layers: 2
num_bidirectional_layers: 4

pad_attention_bias_value: -1000.0
