defaults:
  - llama3p2-1b
  - override sharding: recurrent-fsdp
  - override remat: recurrent
  - _self_


type: recurrent.RecurrentModel


fast_weight_size: 1024
base_lr: 3e-4

grad_rms_eps: 1.0e-12

num_bidirectional_layers: 4
pad_attention_bias_value: -1000.0
